"""initial_schema

Revision ID: 3034d14d664d
Revises: 
Create Date: 2026-07-06 21:53:53.010734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3034d14d664d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anchor_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('anchor_type', sa.String(length=50), nullable=False),
    sa.Column('source_event_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tx_hash', sa.String(length=255), nullable=True),
    sa.Column('aptos_sequence_number', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_anchor_idempotency')
    )
    op.create_index(op.f('ix_anchor_records_status'), 'anchor_records', ['status'], unique=False)
    op.create_index(op.f('ix_anchor_records_user_id'), 'anchor_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anchor_records_user_id'), table_name='anchor_records')
    op.drop_index(op.f('ix_anchor_records_status'), table_name='anchor_records')
    op.drop_table('anchor_records')
    # ### end Alembic commands ###
