"""initial_schema

Revision ID: 9d41b554db10
Revises: 
Create Date: 2026-07-06 21:44:28.919257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d41b554db10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bounties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('skill_coin_reward', sa.Integer(), nullable=False),
    sa.Column('posted_by_id', sa.String(length=36), nullable=False),
    sa.Column('claimed_by_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('escrow_held', sa.Boolean(), nullable=False),
    sa.Column('escrow_released', sa.Boolean(), nullable=False),
    sa.Column('completion_idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('skill_coin_reward > 0', name='ck_bounty_positive_reward'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bounties_posted_by_id'), 'bounties', ['posted_by_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_published'), 'outbox_events', ['published'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_events_published'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_bounties_posted_by_id'), table_name='bounties')
    op.drop_table('bounties')
    # ### end Alembic commands ###
